import logging
import re
from typing import Dict, Any, List, Optional
from datetime import datetime

from .types import (
    SynthesisResult,
    SubTaskResult,
    TeamMessage,
)

logger = logging.getLogger(__name__)


SYNTHESIS_PROMPT_TEMPLATE = """You are synthesizing results from multiple sub-agents into a coherent final output.

## Original Task
{original_instruction}

## Sub-Agent Results
{results_summary}

## Instructions
1. Integrate the findings from all sub-agents
2. Resolve any contradictions or conflicts
3. Provide a comprehensive, well-structured response
4. Cite sources using paper IDs where applicable
5. Highlight key insights and conclusions

Provide your synthesized response:
"""


class ResultSynthesizer:
    """Synthesizer for combining results from multiple sub-agents."""
    
    def __init__(self, max_result_length: int = 2000):
        self._max_result_length = max_result_length
    
    def synthesize(
        self,
        original_instruction: str,
        subtask_results: List[SubTaskResult],
        format_type: str = "report",
    ) -> SynthesisResult:
        logger.info(f"[Synthesizer] Synthesizing {len(subtask_results)} results")
        
        if not subtask_results:
            return SynthesisResult(
                output="No results to synthesize.",
                sources=[],
                confidence=0.0,
                needs_more_info=True,
                follow_up_questions=["Please provide more information about your request."],
            )
        
        successful_results = [
            r for r in subtask_results
            if r.status == "completed" and r.result
        ]
        
        failed_results = [
            r for r in subtask_results
            if r.status == "failed"
        ]
        
        if not successful_results:
            error_msgs = [r.error or "Unknown error" for r in failed_results]
            return SynthesisResult(
                output=f"All sub-tasks failed. Errors: {'; '.join(error_msgs)}",
                sources=[],
                confidence=0.0,
                needs_more_info=True,
                follow_up_questions=["Please try again with a different approach."],
            )
        
        results_summary = self._build_results_summary(successful_results)
        
        output = self._generate_output(
            original_instruction=original_instruction,
            results_summary=results_summary,
            format_type=format_type,
        )
        
        sources = self._extract_sources(successful_results)
        confidence = self._calculate_confidence(successful_results, failed_results)
        needs_more_info = self._assess_completeness(output, original_instruction)
        follow_ups = self._generate_follow_ups(output, original_instruction) if needs_more_info else []
        
        return SynthesisResult(
            output=output,
            sources=sources,
            confidence=confidence,
            needs_more_info=needs_more_info,
            follow_up_questions=follow_ups,
        )
    
    def _build_results_summary(
        self,
        results: List[SubTaskResult],
    ) -> str:
        summary_parts = []
        
        for i, result in enumerate(results, 1):
            agent_id = result.agent_id or "unknown"
            content = result.result or ""
            
            if len(content) > self._max_result_length:
                content = content[:self._max_result_length] + "\n...[truncated]"
            
            summary_parts.append(f"### Result {i} from {agent_id}")
            summary_parts.append(content)
            summary_parts.append("")
        
        return "\n".join(summary_parts)
    
    def _generate_output(
        self,
        original_instruction: str,
        results_summary: str,
        format_type: str,
    ) -> str:
        if format_type == "report":
            return self._format_as_report(original_instruction, results_summary)
        elif format_type == "summary":
            return self._format_as_summary(results_summary)
        elif format_type == "comparison":
            return self._format_as_comparison(results_summary)
        else:
            return self._format_as_report(original_instruction, results_summary)
    
    def _format_as_report(
        self,
        instruction: str,
        results_summary: str,
    ) -> str:
        return f"""# Research Report

## Original Query
{instruction}

## Findings
{results_summary}

## Summary
The above results have been synthesized from multiple specialized agents. Each agent contributed their expertise to provide comprehensive coverage of the research topic.

---
*Generated by XivMind Team System*
"""
    
    def _format_as_summary(self, results_summary: str) -> str:
        lines = results_summary.split("\n")
        key_points = []
        
        for line in lines:
            line = line.strip()
            if line and not line.startswith("#"):
                if len(line) > 50:
                    key_points.append(f"- {line[:200]}...")
                else:
                    key_points.append(f"- {line}")
        
        if len(key_points) > 10:
            key_points = key_points[:10]
        
        return "## Key Findings\n\n" + "\n".join(key_points)
    
    def _format_as_comparison(self, results_summary: str) -> str:
        return f"""# Comparison Analysis

{results_summary}

## Comparative Summary
The results above provide comparative insights across different aspects of the research topic.

---
*Generated by XivMind Team System*
"""
    
    def _extract_sources(self, results: List[SubTaskResult]) -> List[str]:
        sources = []
        paper_id_pattern = r'\b\d{4}\.\d{4,5}(?:v\d+)?\b'
        
        for result in results:
            content = result.result or ""
            found_ids = re.findall(paper_id_pattern, content)
            sources.extend(found_ids)
        
        return list(set(sources))
    
    def _calculate_confidence(
        self,
        successful: List[SubTaskResult],
        failed: List[SubTaskResult],
    ) -> float:
        if not successful and not failed:
            return 0.0
        
        total = len(successful) + len(failed)
        success_rate = len(successful) / total if total > 0 else 0
        
        avg_result_length = 0
        if successful:
            avg_result_length = sum(len(r.result or "") for r in successful) / len(successful)
        
        length_factor = min(avg_result_length / 500, 1.0)
        
        confidence = (success_rate * 0.7) + (length_factor * 0.3)
        
        return round(confidence, 2)
    
    def _assess_completeness(
        self,
        output: str,
        instruction: str,
    ) -> bool:
        incomplete_indicators = [
            "no results",
            "not found",
            "insufficient",
            "incomplete",
            "need more",
            "requires additional",
        ]
        
        output_lower = output.lower()
        
        for indicator in incomplete_indicators:
            if indicator in output_lower:
                return True
        
        return len(output) < 200
    
    def _generate_follow_ups(
        self,
        output: str,
        instruction: str,
    ) -> List[str]:
        follow_ups = []
        
        if "no results" in output.lower():
            follow_ups.append("Would you like to try a different search approach?")
        
        if "compare" in instruction.lower() and "vs" not in output.lower():
            follow_ups.append("Would you like a more detailed comparison between the topics?")
        
        if len(output) < 300:
            follow_ups.append("Would you like me to expand on any particular aspect?")
        
        return follow_ups[:3]
    
    def merge_results(
        self,
        results: List[Dict[str, Any]],
        deduplicate: bool = True,
    ) -> str:
        if not results:
            return ""
        
        merged_parts = []
        seen_content = set() if deduplicate else None
        
        for result in results:
            content = result.get("result", result.get("output", ""))
            
            if deduplicate:
                content_hash = hash(content[:200])
                if content_hash in seen_content:
                    continue
                seen_content.add(content_hash)
            
            merged_parts.append(content)
        
        return "\n\n---\n\n".join(merged_parts)
    
    def compress_result(
        self,
        result: str,
        max_length: int = 1000,
    ) -> str:
        if len(result) <= max_length:
            return result
        
        sentences = result.replace("。", ".\n").replace("！", "!\n").replace("？", "?\n").split("\n")
        
        compressed_parts = []
        current_length = 0
        
        for sentence in sentences:
            sentence = sentence.strip()
            if not sentence:
                continue
            
            if current_length + len(sentence) > max_length:
                break
            
            compressed_parts.append(sentence)
            current_length += len(sentence)
        
        compressed = " ".join(compressed_parts)
        
        if len(compressed) < len(result):
            compressed += "..."
        
        return compressed
