export const ROUTES = {
  HOME: '/',
  LISTINGS: '/listings',
  SEARCH: '/search',
  PAPER_DETAIL: '/paper/:id',
  SETTINGS: '/settings',
  BOOKMARKS: '/bookmarks',
  FOLLOWED_AUTHORS: '/followed-authors',
  DOWNLOADS: '/downloads',
  ASSISTANT: '/assistant',
  AUTHOR_RANKING: '/author-ranking',
  DATA_MANAGER: '/data-manager',
  SKILLS: '/skills',
  SUBAGENTS: '/subagents',
  MEMORY: '/memory',
  TEAM: '/team',
  READER: '/reader/:paperId',
  AUTHOR_PAPERS: '/author/:authorName',
  AUTHOR_PROFILE: '/author/:authorName/profile',
  DAILY_ANALYSIS: '/daily-analysis/:date',
} as const

export const ROUTE_NAMES = {
  HOME: 'Home',
  LISTINGS: 'Listings',
  SEARCH: 'Search',
  PAPER_DETAIL: 'PaperDetail',
  SETTINGS: 'Settings',
  BOOKMARKS: 'Bookmarks',
  FOLLOWED_AUTHORS: 'FollowedAuthors',
  DOWNLOADS: 'Downloads',
  ASSISTANT: 'Assistant',
  AUTHOR_RANKING: 'AuthorRanking',
  DATA_MANAGER: 'DataManager',
  SKILLS: 'SkillManager',
  SUBAGENTS: 'SubAgentManager',
  MEMORY: 'Memory',
  TEAM: 'TeamManager',
  READER: 'PdfReader',
  AUTHOR_PAPERS: 'AuthorPapers',
  AUTHOR_PROFILE: 'AuthorProfile',
  DAILY_ANALYSIS: 'DailyAnalysis',
} as const
