export const DESKTOP_CONFIG = {
  GRID_SIZE: 80,
  MAX_WIDTH: 800,
  ICON_SIZE: 80,
  ICON_CENTER_OFFSET: 40,
  DROP_DISTANCE_THRESHOLD: 50,
  TOOLTIP_WIDTH: 320,
  TOOLTIP_HEIGHT: 200,
  TOOLTIP_GAP: 10,
  TOOLBAR_HEIGHT: 41,
  BORDER_SIZE: 2,
} as const
